<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login – SIT Mutiara Quran</title>
    <meta name="description" content="Login Administrator SIT Mutiara Quran">

    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    @vite(['resources/css/app.css'])

    <style>
        /* Custom styling for background image with specific overlay gradients */
        .login-bg-overlay {
            background-image: linear-gradient(to right, rgba(15, 23, 42, 0.90), rgba(30, 58, 95, 0.75), rgba(15, 23, 42, 0.55)), url('{{ asset('images/fotosekolah.jpg') }}');
        }

        /* Specific CSS rules to scale captcha images generated by the package */
        #captcha-img-container img {
            height: 32px !important;
            width: auto !important;
            border-radius: 6px;
            mix-blend-mode: multiply;
            filter: contrast(1.15) brightness(0.95);
        }

        /* Animations */
        @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
        }
        @keyframes slideFromLeft {
            from { opacity: 0; transform: translateX(-40px); }
            to { opacity: 1; transform: translateX(0); }
        }
        @keyframes slideFromRight {
            from { opacity: 0; transform: translateX(40px); }
            to { opacity: 1; transform: translateX(0); }
        }
        @keyframes scaleUp {
            from { opacity: 0; transform: scale(0.92); }
            to { opacity: 1; transform: scale(1); }
        }

        .animate-fade-in {
            animation: fadeIn 500ms cubic-bezier(0.16, 1, 0.3, 1) forwards;
        }
        .animate-slide-left {
            animation: slideFromLeft 500ms cubic-bezier(0.16, 1, 0.3, 1) forwards;
        }
        .animate-slide-right {
            animation: slideFromRight 500ms cubic-bezier(0.16, 1, 0.3, 1) forwards;
        }
        .animate-scale-up {
            animation: scaleUp 500ms cubic-bezier(0.16, 1, 0.3, 1) forwards;
        }

        /* Spinning loading indicator */
        @keyframes spin {
            from { transform: rotate(0deg); }
            to { transform: rotate(360deg); }
        }
        .animate-spin-custom {
            animation: spin 1.2s linear infinite;
        }
    </style>
</head>
<body class="min-h-screen w-full flex items-center justify-center font-['Poppins'] text-slate-100 bg-slate-900 select-none overflow-x-hidden relative">

    <!-- Fullscreen Background Image with Navy Overlay -->
    <div class="absolute inset-0 bg-cover bg-center login-bg-overlay z-0 animate-fade-in pointer-events-none"></div>

    <!-- Content Wrapper -->
    <div class="relative z-10 w-full min-h-screen flex items-center justify-center p-4 sm:p-8 lg:p-12">
        <div class="w-full max-w-6xl grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-16 items-center">
            
            <!-- LEFT PANEL: Branding (Desktop/Tablet) -->
            <div class="hidden lg:flex lg:col-span-6 flex-col justify-center text-left text-white animate-slide-left pr-4">
                <div class="flex items-center gap-4 mb-4">
                    <div class="w-16 h-16 rounded-2xl bg-white/10 backdrop-blur-md p-2 flex items-center justify-center border border-white/20 shadow-lg shrink-0">
                        <img src="{{ asset('images/logomq.jpg') }}" alt="Logo Sekolah" class="w-12 h-12 object-contain rounded-lg">
                    </div>
                    <div>
                        <h1 class="text-3xl font-black tracking-wider uppercase text-amber-400 leading-none">SIT Mutiara Quran</h1>
                        <p class="text-sm font-semibold tracking-wide text-slate-200 mt-1">Sistem Informasi Manajemen Sekolah</p>
                    </div>
                </div>
                <div class="h-[3px] w-24 bg-gradient-to-r from-amber-400 to-transparent my-6 rounded-full"></div>
                <p class="text-lg sm:text-xl font-medium italic text-slate-200 leading-relaxed max-w-md">
                    "Membangun Generasi Qurani, Berprestasi, dan Berkarakter."
                </p>
            </div>

            <!-- RIGHT PANEL: Login Card -->
            <div class="w-full lg:col-span-6 flex items-center justify-center">
                <div class="w-full max-w-[390px] bg-white/15 backdrop-blur-xl border border-white/20 rounded-3xl p-5 sm:p-6 shadow-2xl flex flex-col relative animate-slide-right">
                    
                    <!-- Mobile Branding (Only visible on mobile screens) -->
                    <div class="flex lg:hidden flex-col items-center text-center mb-4 shrink-0">
                        <img src="{{ asset('images/logomq.jpg') }}" alt="Logo Sekolah" class="w-12 h-12 object-contain rounded-xl bg-white/10 border border-white/20 p-1.5 shadow-md mb-2">
                        <h1 class="text-xl font-black uppercase text-amber-400 tracking-wider">SIT Mutiara Quran</h1>
                        <p class="text-[11px] font-semibold text-slate-200">Sistem Informasi Manajemen Sekolah</p>
                        <p class="text-[11px] italic text-slate-300 mt-1 font-medium">"Membangun Generasi Qurani, Berprestasi, dan Berkarakter."</p>
                        <div class="w-12 h-px bg-white/20 my-3"></div>
                    </div>

                    <!-- CARD HEADER -->
                    <div class="flex flex-col items-center text-center mb-4">
                        <div class="w-12 h-12 rounded-xl bg-gradient-to-br from-amber-400/20 to-amber-500/10 border border-amber-400/30 flex items-center justify-center text-amber-400 mb-2 shadow-lg">
                            <i class="fas fa-user-shield text-xl"></i>
                        </div>
                        <h2 class="text-lg font-bold text-white tracking-wide">Admin Portal</h2>
                        <p class="text-[11px] text-slate-300 mt-0.5">Masuk ke panel administrator</p>
                    </div>

                    <!-- ERROR MESSAGE -->
                    @if ($errors->any())
                        <div class="mb-3 p-3 rounded-xl bg-red-500/20 border border-red-500/30 text-red-200 text-[11px] flex items-center gap-2">
                            <i class="fas fa-circle-exclamation text-red-400 shrink-0"></i>
                            <span>{{ $errors->first() }}</span>
                        </div>
                    @endif

                    <!-- FORM -->
                    <form method="POST" action="{{ route('admin.login.post') }}" id="adminLoginForm" class="space-y-3.5">
                        @csrf
                        <input type="hidden" name="role" value="admin">

                        <!-- Username Input -->
                        <div class="flex flex-col gap-1">
                            <label for="admin_login" class="text-[10px] font-bold text-slate-300 tracking-wide uppercase">Username</label>
                            <div class="relative flex items-center">
                                <i class="fa fa-user absolute left-4 text-slate-400 text-xs"></i>
                                <input type="text" name="login" id="admin_login" 
                                       class="w-full bg-slate-950/40 border border-white/10 rounded-xl py-2.5 pl-10 pr-4 text-xs text-white placeholder-slate-400 focus:outline-none focus:border-amber-400 focus:ring-1 focus:ring-amber-400 transition-all duration-300 h-10"
                                       placeholder="Masukkan username admin" autocomplete="off" required>
                            </div>
                        </div>

                        <!-- Password Input -->
                        <div class="flex flex-col gap-1">
                            <label for="admin_password" class="text-[10px] font-bold text-slate-300 tracking-wide uppercase">Password</label>
                            <div class="relative flex items-center">
                                <i class="fa fa-lock absolute left-4 text-slate-400 text-xs"></i>
                                <input type="password" name="password" id="admin_password" 
                                       class="w-full bg-slate-950/40 border border-white/10 rounded-xl py-2.5 pl-10 pr-10 text-xs text-white placeholder-slate-400 focus:outline-none focus:border-amber-400 focus:ring-1 focus:ring-amber-400 transition-all duration-300 h-10"
                                       placeholder="Masukkan password" required>
                                <button type="button" id="adminToggle" class="absolute right-4 text-slate-400 hover:text-white transition-colors duration-300">
                                    <i class="fa-solid fa-eye text-xs"></i>
                                </button>
                            </div>
                        </div>

                        <!-- Math CAPTCHA Container -->
                        <div class="flex flex-col gap-1">
                            <label for="captcha" class="text-[10px] font-bold text-slate-300 tracking-wide uppercase">Math CAPTCHA</label>
                            <div class="flex items-center gap-2">
                                <div class="bg-gradient-to-r from-purple-500/20 via-orange-500/20 to-blue-500/20 backdrop-blur-md rounded-xl px-2 py-1.5 border border-white/10 flex items-center justify-center shrink-0 min-w-[100px] select-none h-10 relative overflow-hidden" id="captcha-img-container">
                                    {!! preg_replace('/src="https?:\/\/[^\/]+/', 'src="', captcha_img('math')) !!}
                                </div>
                                <button type="button" class="w-10 h-10 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center text-slate-300 hover:bg-white/10 hover:text-white transition-all duration-300 shrink-0" id="btn-refresh-captcha" title="Refresh Captcha">
                                    <i class="fa-solid fa-arrows-rotate text-xs" id="refresh-icon"></i>
                                </button>
                                <div class="relative flex-grow">
                                    <i class="fa-solid fa-calculator absolute left-3.5 text-slate-400 text-xs"></i>
                                    <input type="text" name="captcha" id="captcha" 
                                           class="w-full bg-slate-950/40 border border-white/10 rounded-xl py-2.5 pl-10 pr-4 text-xs text-white placeholder-slate-400 focus:outline-none focus:border-amber-400 focus:ring-1 focus:ring-amber-400 transition-all duration-300 h-10"
                                           placeholder="Hasil" autocomplete="off" required>
                                </div>
                            </div>
                        </div>

                        <!-- Submit Button -->
                        <button type="submit" class="w-full bg-gradient-to-r from-blue-900 to-blue-950 border border-blue-800 text-white font-bold py-3 rounded-xl hover:scale-[1.02] hover:shadow-xl hover:shadow-blue-950/40 active:scale-95 transition-all duration-300 flex items-center justify-center gap-2 z-10 animate-scale-up text-xs" id="adminBtn">
                            <span id="adminBtnText" class="flex items-center gap-2">
                                <i class="fas fa-sign-in-alt"></i> Masuk sebagai Admin
                            </span>
                        </button>
                    </form>

                    <!-- BACK LINK -->
                    <a href="{{ route('login') }}" class="mt-4 text-[11px] font-semibold text-slate-300 hover:text-amber-400 flex items-center justify-center gap-2 transition-colors duration-300">
                        <i class="fas fa-arrow-left"></i> Kembali ke Login Siswa/Guru
                    </a>

                </div>
            </div>

        </div>
    </div>

    <!-- Script Section -->
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const toggle = document.getElementById("adminToggle");
            const pass = document.getElementById("admin_password");
            const form = document.getElementById("adminLoginForm");
            const btn = document.getElementById("adminBtn");
            const btnTxt = document.getElementById("adminBtnText");

            // Password field toggle visibility
            toggle.addEventListener("click", () => {
                const icon = toggle.querySelector("i");
                if (pass.type === "password") {
                    pass.type = "text";
                    icon.className = "fa-solid fa-eye-slash text-sm";
                } else {
                    pass.type = "password";
                    icon.className = "fa-solid fa-eye text-sm";
                }
            });

            // Form submit loading visual
            form.addEventListener("submit", () => {
                btn.disabled = true;
                btn.classList.add("opacity-90", "cursor-not-allowed");
                btnTxt.innerHTML = '<i class="fas fa-spinner animate-spin-custom"></i> Memproses...';
            });

            // Captcha refresh handler
            const refreshBtn = document.getElementById("btn-refresh-captcha");
            const refreshIcon = document.getElementById("refresh-icon");
            const captchaImgContainer = document.getElementById("captcha-img-container");

            if (refreshBtn && captchaImgContainer) {
                refreshBtn.addEventListener("click", () => {
                    refreshCaptcha();
                });
            }

            function refreshCaptcha() {
                if (!refreshBtn || !captchaImgContainer || !refreshIcon) return;

                refreshIcon.classList.add("animate-spin-custom");
                refreshBtn.disabled = true;

                fetch(`/refresh-captcha?t=${Date.now()}`)
                    .then(response => {
                        if (!response.ok) throw new Error("Gagal refresh captcha");
                        return response.json();
                    })
                    .then(data => {
                        if (data.captcha) {
                            captchaImgContainer.innerHTML = data.captcha;
                        }
                    })
                    .catch(error => {
                        console.error("Error refreshing captcha:", error);
                    })
                    .finally(() => {
                        setTimeout(() => {
                            refreshIcon.classList.remove("animate-spin-custom");
                            refreshBtn.disabled = false;
                        }, 400);
                    });
            }
        });
    </script>
</body>
</html>
